Migrate to 12.0 :camel:
axonivy-market/sbb-connector pull request #21
Opened 2024-12-02 13:06 UTC by ivy-rew

A friendly conversion provided by market-up2date-keeper :robot: :handshake:

2025-01-02 06:44 UTC, ivy-rew commented on sbb-connector-demo/config/variables.yaml
> +    requestor: 'tester'
we never add data to the demo/variables.yaml

2025-01-02 06:55 UTC, phhung-axonivy commented on sbb-connector-demo/config/variables.yaml
> +    requestor: 'tester'
Thanks for your feedback. I will move these values into variables.

2025-01-02 09:51 UTC, phhung-axonivy commented on sbb-connector-demo/config/variables.yaml
> +    requestor: 'tester'
Hi @ivy-rew 
I tried to move these values into variables and adapted on the test source butthe variables can not be changed in the runtime.
So I just remove some redundant variables and update value for new one in demo/variables.yaml from the previous version.

2025-01-02 11:09 UTC, ivy-rew commented on sbb-connector-demo/config/variables.yaml
> +    requestor: 'tester'
but you still have data in the demo ...can't we just migrate the URI into the test/config/variables.yaml and have everything working? :thinking:

2025-01-03 02:08 UTC, phhung-axonivy commented on sbb-connector-demo/config/variables.yaml
> +    requestor: 'tester'
I'm sorry for misunderstanding.
I removed data in the demo project and moved it to config/variables.yaml of 2 test projects.

2025-01-03 02:36 UTC, ntqdinh-axonivy requested changes

2025-01-03 08:58 UTC, ntqdinh-axonivy approved these changes
LGTM

2025-01-03 09:14 UTC, merged